package com.myspace.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Risk implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "RISK_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "RISK_ID_SEQ", name = "RISK_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.Integer value;

	public Risk() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getValue() {
		return this.value;
	}

	public void setValue(java.lang.Integer value) {
		this.value = value;
	}

	public Risk(java.lang.Long id, java.lang.Integer value) {
		this.id = id;
		this.value = value;
	}

}